title: Eat the Rainbow! Catering
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Healthy, wholesome, and uniquely delicious plant-based vegan catering and meals. Serving the Portland, Oregon area.
baseurl: ""
url: "http://eattherainbowcatering.com"
github_username:  amychurchwell

plugins:
  - jekyll-feed
  - jekyll-seo-tag

data_dir: data

sass:
  sass_dir: _sass
  style: compact

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
