backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/images"
collections:
- name: menu
  label: menu
  files:
    - label: "Menu"
      name: "menu"
      file: "data/menu.yml"
      widget: list
      fields:
        - {label: Name, name: name, widget: string}
        - {label: Ingredients, name: ingredients, widget: string}